name: ðŸ“š Latest Hashnode blog posts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *' # Runs Every 24 Hours


jobs:
  update-readme-with-blog:
    name: Update repo README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Hashnode.com blog posts
        uses: hossainchisty/update-hashnode-blog@v1.0
        with:
          comment_tag_name: "HASHNODE"
          feed_list: "https://hossainchisty.hashnode.dev/rss.xml"
          commit_message: "Update hashnode.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
